version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: cobolexamplepw
      POSTGRES_DB: cobolexample
    ports:
      - '5432:5432'

volumes:
  db-data:
