version: '3.8'

services:
  express-backend:
    build:
      context: .
      dockerfile: Dockerfile.express
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      VUE_APP_API_BASE_URL: ${VUE_APP_API_BASE_URL}
      VUE_APP_WEBSOCKET_BASE_URL: ${VUE_APP_WEBSOCKET_BASE_URL}
    depends_on:
      - db

  go-backend:
    build:
      context: .
      dockerfile: Dockerfile.golang
    ports:
      - '3001:3001'
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:cobolexamplepw@db:5432/cobolexample
      REDIS_ADDR: redis:6379

  db:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: cobolexamplepw
      POSTGRES_DB: cobolexample
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  db-data:
